# Generated by Django 2.1.5 on 2019-02-15 04:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('raw_content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.User')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='posts.Comment')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_content', models.TextField()),
                ('content_type', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('comments', models.IntegerField(default=0)),
                ('author_name', models.CharField(max_length=16)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.User')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_value', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='PostTagPivot',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'db_table': 'post_tag_pivot',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.PositiveSmallIntegerField()),
                ('vote_value', models.SmallIntegerField()),
                ('object_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.User')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
