# Generated by Django 2.1.5 on 2019-02-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_temp',
            new_name='Comment',
        ),
    ]
