# Generated by Django 2.1.5 on 2019-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
                ('secret', models.CharField(max_length=32)),
                ('user_ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('user_perms', models.TextField(default='user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
